export const USER ={
    LOG_IN:'LOG_IN',
    LOG_OUT:'LOG_OUT'
}
export const REGISTRATION_FORM={
    SHOW_REGISTRATION_FORM:'SHOW_REGISTRATION_FORM',  
}

export const STATES_OF_APPLICATION={
    SHOW_LOADING:'SHOW_LOADING',
    HIDE_LOADING:'HIDE_LOADING',
    SHOW_SUCCESSFUL:' SHOW_SUCCESSFUL',
    HIDE_SUCCESSFUL:' HIDE_SUCCESSFUL',
    SHOW_ERORR:'ERROR',
    HIDE_ERROR:'HIDE_ERROR',
}

export const SEARCH_CITY='SEARCH_CITY'
export const CLEAN_SEARCH="CLEAN_SEARCH"
export const ADD_CITY="ADD_CITY"
export const REMOVE_CITY="REMOVE_CITY"